services:
  stockd:
    build: .
    ports:
      - "8080:80"
    volumes:
      - stockd-db:/var/www/html/db
    environment:
      - AUTH_PASSWORD_HASH=${AUTH_PASSWORD_HASH}
    restart: unless-stopped

volumes:
  stockd-db:
