services:
  stockd:
    build: .
    ports:
      - "8012:80"
    volumes:
      - stockd-db:/var/www/html/db
    environment:
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    restart: unless-stopped

volumes:
  stockd-db:
